### ISSUE TITLE
INFOGRAFIA DE REQUERIMIENTOS

### ISSUE THREAD

**Issue by Anamichel-leon** [SistemasTecTlaxiaco/actividad-1-infografia-Anamichel-leon-1#1]
[INFOGRAFIA DE REQUERIMIENTOS.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-Anamichel-leon-1/files/14249721/INFOGRAFIA.DE.REQUERIMIENTOS.pdf)

**Comment by josealfredo79** [comment]
Calificacion 20
